/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tourist_guide;

/**
 *
 * @author ARUN
 */
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
public class SelectPlace extends javax.swing.JFrame {

    /**
     * Creates new form SelectPlace
     */
    private Connection conn;
    private Statement stmt;
    private ResultSet rs;
    private int flag,cid;
    private String uname;
    public SelectPlace(int flag,String uname,int cid) {
        try {
            initComponents();
            conn = null;
            stmt = null;
            rs = null;
            try {
                Class.forName("org.apache.derby.jdbc.ClientDriver");
            } catch (ClassNotFoundException e) {
                System.out.println("Class not found " + e);
            }
            System.out.println("JDBC Class found");
            try {
                conn = DriverManager.getConnection("jdbc:derby://localhost:1527//JD", "arunjd_07", "jagan");
                stmt = conn.createStatement();
            } catch (SQLException e) {
                System.out.print("conn" + e.getMessage());
            }
            this.cid=cid;
            this.flag=flag;
            this.uname=uname;
            if(flag==1){
                jLabel2.setText("The tourist spots in your city are given below. Select a hotel to view the details");
                rs=stmt.executeQuery("select name from touristspots where cityid=(select currentcity from tourist where uname like '"+uname+"')");
                DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
                while(rs.next()){
                    model.addElement(rs.getString("name"));
                }
                jComboBox1.setModel(model);
            }
            else if(flag==2){
                jLabel2.setText("The hotels in your city are given below. Select a hotel to view the details");
                rs=stmt.executeQuery("select name from hotel where city=(select currentcity from tourist where uname like '"+uname+"')");
                DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
                while(rs.next()){
                    model.addElement(rs.getString("name"));
                }
                jComboBox1.setModel(model);
            }
            else if(flag==3){
                jLabel2.setText("The restaurants in your city are given below. Select a hotel to view the details");
                rs=stmt.executeQuery("select name from restaurant where city=(select currentcity from tourist where uname like '"+uname+"')");
                DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
                while(rs.next()){
                    model.addElement(rs.getString("name"));
                }
                jComboBox1.setModel(model);
            }
            else{
                rs=stmt.executeQuery("select name from touristspots where cityid="+cid+"");
                DefaultComboBoxModel model = (DefaultComboBoxModel)jComboBox1.getModel();
                while(rs.next()){
                    model.addElement(rs.getString("name"));
                }
                jComboBox1.setModel(model);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectPlace.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                    Results");

        jLabel2.setText("The hotels in your city are given below. Select a hotel to view the details");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());

        jButton1.setText("Get details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id=jComboBox1.getSelectedIndex(),count=0;
        try {
            if(flag==1){
                rs=stmt.executeQuery("select id from touristspots where cityid=(select currentcity from tourist where uname like '"+uname+"')");
                while(count<=id){
                    rs.next();
                    count++;
                }
                id=Integer.parseInt(rs.getString("id"));
                SpotDetails sd=new SpotDetails(id,uname);
                this.setVisible(false);
                sd.setVisible(true);
            }
            else if(flag==2){
                rs=stmt.executeQuery("select hotelid from hotel where city=(select currentcity from tourist where uname like '"+uname+"')");
                while(count<=id){
                    rs.next();
                    count++;
                }
                id=Integer.parseInt(rs.getString("hotelid"));
                HotelDetails hd=new HotelDetails(id,uname);
                this.setVisible(false);
                hd.setVisible(true);
            }
            else if(flag==3){
                rs=stmt.executeQuery("select resid from restaurant where city=(select currentcity from tourist where uname like '"+uname+"')");
                while(count<=id){
                    rs.next();
                    count++;
                }
                id=Integer.parseInt(rs.getString("resid"));
                RestaurantDetails rd=new RestaurantDetails(id,uname);
                this.setVisible(false);
                rd.setVisible(true);
            }
            else{
                rs=stmt.executeQuery("select id from touristspots where cityid="+cid+"");
                while(count<=id){
                    rs.next();
                    count++;
                }
                id=Integer.parseInt(rs.getString("id"));
                SpotDetails sd=new SpotDetails(id,uname);
                this.setVisible(false);
                sd.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectPlace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectPlace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPlace(0,null,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
